# Generated by Django 4.0 on 2022-12-01 23:58

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('acl_inherit', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navMenu.navmenu')),
            ],
            options={
                'unique_together': {('parent', 'id')},
            },
        ),
        migrations.CreateModel(
            name='NavMenuAcl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acl_target', models.CharField(max_length=50)),
                ('acl_target_name', models.CharField(max_length=100)),
                ('acl_target_name_en', models.CharField(max_length=100)),
                ('acl_value', models.IntegerField()),
                ('acl_value_name', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navMenu.navmenu')),
            ],
            options={
                'unique_together': {('parent', 'acl_target')},
            },
        ),
    ]
