# Generated by Django 4.0 on 2022-10-28 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField()),
                ('menu_name', models.CharField(max_length=50)),
                ('acc_type1', models.CharField(blank=True, max_length=50)),
                ('acc_type2', models.CharField(blank=True, max_length=50)),
                ('acc_type3', models.CharField(blank=True, max_length=50)),
                ('acc_type4', models.CharField(blank=True, max_length=2000)),
                ('acc_type5', models.CharField(blank=True, max_length=500)),
                ('user_empno', models.CharField(blank=True, max_length=50)),
                ('user_name', models.CharField(blank=True, max_length=50)),
                ('user_name_en', models.CharField(blank=True, max_length=50)),
                ('user_mail', models.CharField(blank=True, max_length=50)),
                ('user_posi', models.CharField(blank=True, max_length=50)),
                ('user_posi_en', models.CharField(blank=True, max_length=50, null=True)),
                ('user_org', models.CharField(blank=True, max_length=100)),
                ('user_org_en', models.CharField(blank=True, max_length=100)),
                ('acc_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MailingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_command', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=100)),
                ('item_title', models.CharField(blank=True, max_length=200, null=True)),
                ('item_comments', models.CharField(max_length=2000)),
                ('from_user', models.CharField(max_length=200)),
                ('to_user_list', models.CharField(max_length=2000)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
