# Generated by Django 4.0 on 2022-10-17 01:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(default=0)),
                ('group_id', models.IntegerField()),
                ('indent', models.IntegerField(default=0)),
                ('order_no', models.IntegerField(default=1)),
                ('div_name', models.CharField(default='', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('owner_empno', models.CharField(max_length=50)),
                ('owner_mail', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_name_en', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('group_modify_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hit_count', models.IntegerField(default=0)),
                ('agree_count', models.IntegerField(default=0)),
                ('answer_count', models.IntegerField(default=0)),
                ('attached_count', models.IntegerField(default=0)),
                ('contents', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('board_type', models.CharField(max_length=10)),
                ('board_mailing', models.CharField(blank=True, max_length=1000)),
                ('reply_yn', models.BooleanField(default=False)),
                ('comments_yn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BoardPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_name', models.CharField(default='', max_length=50)),
                ('target_id', models.IntegerField(blank=True)),
                ('popup_sdate', models.DateField(null=True)),
                ('popup_edate', models.DateField(null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
        ),
        migrations.CreateModel(
            name='BoardComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=4000)),
                ('owner_empno', models.CharField(max_length=50)),
                ('owner_mail', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_name_en', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
        ),
        migrations.CreateModel(
            name='BoardAttached',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(default=1)),
                ('file_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('file_size', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.boardmaster'),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('master', 'id')},
        ),
    ]
