"""
Django settings for djangosite project.

Generated by 'django-sysadmin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yqmcyt&3t7s(2h62d5&30okbsl720nbl!=n_p%tqtlvz9o6wv%'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# INTERNAL_IPS = ['127.0.0.1',]
# ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '10.164.2.25', 'vlab.lge.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'mptt',
    'apps.middleware.apps.AccessHistoryConfig',
    'apps.navMenu.apps.NaveMenuConfig',
    'apps.boards.apps.BoardsConfig',
    'apps.common',
    'apps.statistic',
    'apps.sysadmin',
    'apps.royalty',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.middleware.aclCheckMiddleware.AclCheckMiddleware',
    'apps.middleware.accessHistoryMiddleware.AccessHistoryMiddleware',
]

ROOT_URLCONF = 'djangosite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangosite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # mysqlclient librarly 설치
        'NAME': 'DJ_DEFAULT',
        'USER': 'cmuser',
        'PASSWORD': 'rnjsdhdud1@',  # mariaDB 설치 시 입력한 root 비밀번호 입력
        'HOST': 'localhost',
        'PORT': '3306'
    },
    'cm': {
        'ENGINE': 'django.db.backends.mysql',  # mysqlclient librarly 설치
        'NAME': 'CM',
        'USER': 'cmuser',
        'PASSWORD': 'rnjsdhdud1@',  # mariaDB 설치 시 입력한 root 비밀번호 입력
        'HOST': 'localhost',
        'PORT': '3306'
    },
    'hq': {
        'ENGINE': 'django.db.backends.mysql',  # mysqlclient librarly 설치
        'NAME': 'HQ',
        'USER': 'hquser',
        'PASSWORD': 'rnjsdhdud1@',  # mariaDB 설치 시 입력한 root 비밀번호 입력
        'HOST': 'localhost',
        'PORT': '3306'
    },
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ko-KR'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

# Django 내부적으로 시간대를 인식하는 날짜 및 시간 사용 : True, Local Time 사용 : False
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = '../virtual_static/'  # <-- python manage.py collectstatic
STATICFILES_DIRS = [BASE_DIR / "static", ]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]
MAX_UPLOAD_SIZE = 1024 * 1024 * 1024 * 2
DATA_UPLOAD_MAX_MEMORY_SIZE = None
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024 * 2
DATA_UPLOAD_MAX_NUMBER_FIELDS = None

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'apps.utils.custom_exception_handler'
}

EMAIL_HOST = "lgekrhqmh01.lge.com"
EMAIL_PORT = 25

X_FRAME_OPTIONS = "ALLOW-FROM=http://lge.com/"

# CORS
CORS_ORIGIN_WHITELIST = ['http://dev-apigw-int.lge.com:7220', 'http://apigw-int.lge.com:7210']
CORS_ALLOW_CREDENTIALS = True