# Generated by Django 3.2.6 on 2022-11-17 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='columnMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=50)),
                ('column_name_header', models.CharField(max_length=60)),
                ('order_no', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='modelBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_subsidiary', models.CharField(max_length=10, null=True)),
                ('model_suffix', models.CharField(max_length=30)),
                ('production_model_suffix', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=30, null=True)),
                ('product_lv3', models.CharField(max_length=40, null=True)),
                ('product_lv4', models.CharField(max_length=60, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('period_name', models.CharField(default='202210', max_length=10)),
                ('inch', models.CharField(default='55', max_length=5, null=True)),
                ('series_name1', models.CharField(default='', max_length=5, null=True)),
                ('series_name2', models.CharField(default='', max_length=7, null=True)),
                ('series_name3', models.CharField(default='', max_length=12, null=True)),
                ('model_compr', models.CharField(default='', max_length=15, null=True)),
                ('nano_initial', models.CharField(default='', max_length=5, null=True)),
                ('t2', models.CharField(default='', max_length=2, null=True)),
                ('suffix', models.CharField(default='', max_length=10, null=True)),
                ('suffix_country', models.CharField(default='', max_length=2, null=True)),
                ('country_match', models.CharField(default='', max_length=20, null=True)),
                ('region2', models.CharField(default='', max_length=10, null=True)),
                ('region1', models.CharField(default='', max_length=5, null=True)),
                ('mp3', models.CharField(default='', max_length=5, null=True)),
                ('tech', models.CharField(default='', max_length=5, null=True)),
                ('nlp', models.CharField(default='', max_length=5, null=True)),
                ('odm', models.CharField(default='', max_length=5, null=True)),
                ('product_family', models.CharField(default='', max_length=5, null=True)),
                ('model_id', models.CharField(default='', max_length=50, null=True)),
                ('main_soc', models.CharField(default='', max_length=20, null=True)),
                ('soc_co', models.CharField(default='', max_length=10, null=True)),
                ('sw_service', models.CharField(default='', max_length=30, null=True)),
                ('smart', models.CharField(default='', max_length=10, null=True)),
                ('three_d', models.CharField(default='', max_length=10, null=True)),
                ('mr', models.CharField(default='', max_length=30, null=True)),
                ('wifi_bt', models.CharField(default='', max_length=20, null=True)),
                ('analog', models.CharField(default='', max_length=10, null=True)),
                ('year', models.CharField(default='', max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='modelSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(default=0)),
                ('column_name', models.CharField(max_length=200)),
                ('column_data', models.CharField(max_length=1000)),
                ('column_data_value', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='regionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, null=True)),
                ('country', models.CharField(max_length=40, null=True)),
                ('region1', models.CharField(max_length=10, null=True)),
                ('year', models.CharField(max_length=10, null=True)),
                ('mode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='modelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(default=0)),
                ('column_name', models.CharField(max_length=200)),
                ('column_data', models.CharField(max_length=1000, null=True)),
                ('column_data_value', models.CharField(max_length=1000, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty.modelbasic')),
            ],
        ),
    ]
